### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by akio-outori** [akio-outori/bettermeans#8]
Now that the bettermeans app is starting, we're seeing a number of 500 internal server errors when trying to access the app in a browser.  Most of these so far appear to be related to unsupported ASCII characters in the code base, for example - https://github.com/Bettermeans/bettermeans/blob/master/app/helpers/application_helper.rb#L883

For now we should see if we can normalize these to supported characters to get the application online.

**Comment by akio-outori** [comment]
```
[2018-02-28 23:22:44] ERROR NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.each
	/home/vagrant/.gem/ruby/1.9.1/gems/rack-1.1.6/lib/rack/utils.rb:336:in `initialize'
	/home/vagrant/.gem/ruby/1.9.1/gems/rack-1.1.6/lib/rack/utils.rb:330:in `new'
	/home/vagrant/.gem/ruby/1.9.1/gems/rack-1.1.6/lib/rack/utils.rb:330:in `new'
	/home/vagrant/.gem/ruby/1.9.1/gems/rack-1.1.6/lib/rack/content_length.rb:14:in `call'
	/home/vagrant/.gem/ruby/1.9.1/gems/rack-1.1.6/lib/rack/handler/webrick.rb:48:in `service'
	/usr/share/ruby/1.9/webrick/httpserver.rb:138:in `service'
	/usr/share/ruby/1.9/webrick/httpserver.rb:94:in `run'
	/usr/share/ruby/1.9/webrick/server.rb:191:in `block in start_thread'
```
